seasons = ['summer', 'winter', 'autumn']
season = seasons[0] # which data set to get the values from
timeStep = 60 # in seconds
timeStepADC = 6 # number of measurements per timestep
rampUp = True # interpolate and ramp up the value inbetween the values from the data set
rampUpStep = 60 # how many interpolated values
numberOfDays = 4 # number of days to simulate over, from the data set
column = 'Gg_pyr'
BTmac = '45:D5:34:90:B8:26' #Nordic: 'E0:21:78:85:2A:FB'
BTname = 'SoC BLE'
BTservice = '180d'
BTserviceUUID = '0x180D'
BTinterval = 2.0
MaxLedWatt = 1000 # Max W/m^2 output of LED